#include "PTBLogChannels.h"

DEFINE_LOG_CATEGORY(LogPTBCore);
DEFINE_LOG_CATEGORY(LogPTBFlow);
DEFINE_LOG_CATEGORY(LogPTBProfile);
DEFINE_LOG_CATEGORY(LogPTBRhythm);
DEFINE_LOG_CATEGORY(LogPTBAudio);
DEFINE_LOG_CATEGORY(LogPTBCommon);
DEFINE_LOG_CATEGORY(LogPTBMiniGames);
DEFINE_LOG_CATEGORY(LogPTBTutorial);
DEFINE_LOG_CATEGORY(LogPTBProgression);
DEFINE_LOG_CATEGORY(LogPTBCharacters);
DEFINE_LOG_CATEGORY(LogPTBMultiplayer);
DEFINE_LOG_CATEGORY(LogPTBUI);
DEFINE_LOG_CATEGORY(LogPTBDebug);
DEFINE_LOG_CATEGORY(LogPTBInterfaces);
DEFINE_LOG_CATEGORY(LogPTBWwise);

