#include "PTBLogChannels.h"
DEFINE_LOG_CATEGORY(LogRhythm);
DEFINE_LOG_CATEGORY(LogWwise);
DEFINE_LOG_CATEGORY(LogMulti);
DEFINE_LOG_CATEGORY(LogFlow);
DEFINE_LOG_CATEGORY(LogProfile);
DEFINE_LOG_CATEGORY(LogTutorial);
DEFINE_LOG_CATEGORY(LogProgression);